"""create_phase_3_tables

Revision ID: d52559d95873
Revises: 
Create Date: 2026-09-04 18:49:45.502222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd52559d95873'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doubts')
    op.drop_table('syllabus_nodes')
    op.drop_table('contradiction_alerts')
    op.drop_table('course_materials')
    op.drop_table('material_chunks')
    op.drop_table('doubt_answers')
    op.drop_table('doubt_clusters')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doubt_clusters',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('syllabus_node_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('cluster_title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('module_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('doubt_count', sa.INTEGER(), nullable=True),
    sa.Column('key_misconceptions', sqlite.JSON(), nullable=True),
    sa.Column('suggested_action', sa.TEXT(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['syllabus_node_id'], ['syllabus_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doubt_answers',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('doubt_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('answer_text', sa.TEXT(), nullable=False),
    sa.Column('citations', sqlite.JSON(), nullable=True),
    sa.Column('reasoning_trace', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['doubt_id'], ['doubts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_chunks',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('material_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('syllabus_node_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('chunk_index', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('page_number', sa.INTEGER(), nullable=True),
    sa.Column('embedding', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['course_materials.id'], ),
    sa.ForeignKeyConstraint(['syllabus_node_id'], ['syllabus_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_materials',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('file_url', sa.TEXT(), nullable=True),
    sa.Column('content_text', sa.TEXT(), nullable=False),
    sa.Column('uploaded_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contradiction_alerts',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('topic_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('source_a_title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('source_a_quote', sa.TEXT(), nullable=False),
    sa.Column('source_b_title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('source_b_quote', sa.TEXT(), nullable=False),
    sa.Column('explanation', sa.TEXT(), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('syllabus_nodes',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('parent_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('level', sa.VARCHAR(length=20), nullable=False),
    sa.Column('keywords', sqlite.JSON(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['syllabus_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doubts',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('detected_topic_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('detected_topic_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_syllabus_relevant', sa.BOOLEAN(), nullable=True),
    sa.Column('confidence_score', sa.FLOAT(), nullable=True),
    sa.Column('has_contradiction', sa.BOOLEAN(), nullable=True),
    sa.Column('contradiction_details', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['detected_topic_id'], ['syllabus_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
